after_success: bash <(curl -s https://codecov.io/bash)

before_install: travis_retry composer self-update

branches:
  only: master

cache:
  directories: $HOME/.composer/cache

dist: trusty

install: travis_retry composer install --no-interaction --prefer-dist

language: php

php:
  - 5.6
  - 7.0
  - 7.1

script: vendor/bin/phpunit
